Initial description and example api
project-origin/issuer pull request #1
Opened 2024-02-26 14:56 UTC by MartinSchmidt

This pull request adds a description OriginStamp project,  and example API for issuing GCs.

2024-02-26 15:20 UTC, Mike4Elia approved these changes
Looks good. 

One minor remarks in the 'API Example', There is an example to create the recipient with a Public Key, but there's no mention where this key is coming from.

2024-02-27 06:27 UTC, sahma19 requested changes

2024-02-27 06:27 UTC, sahma19 commented on README.md
> +The GCs are issued by an issuing body and are stored in a registry. And an owner keeps track of their ownership of GC slices in a wallet. The process of issuing a GC is a complex process that involve
Have you thought about the implications, regarding how people will feel when issuance is handled by another entity that is not the TSO?

Right now energinet, being the TSO for Denmark, is also issuing body, using the certificates subsystem.

Having the TSO themselves act as issuing body creates a perception of validity, that cannot be replicated, should one choose to let another entity act as issuing body. While I do understand that the certificates are issued, using measurement data, directly from the TSO (energinet), I still believe that the perceived validity of those issued GC's will decrease. Would like to discuss this further, should you have the time.

2024-02-27 06:51 UTC, tnickelsen commented on README.md
> +The GCs are issued by an issuing body and are stored in a registry. And an owner keeps track of their ownership of GC slices in a wallet. The process of issuing a GC is a complex process that involve
The GCs are not stored in the registry are they? Thought they were registered there and then stored in the wallet

2024-02-27 08:18 UTC, CodeReaper commented on doc/example-api.md
> +## Create a recipient
Can you update a recipient? I am thinking about if a person moves their wallet, or their wallet provider changes their endpoint, etc.

2024-02-27 08:18 UTC, CodeReaper commented on README.md
> +In the Project-Origin Electricity implementation, consists of a fungible and non-fungible digital assets, where the non-fungible assets are called Guarantees of Origin (GCs). The fungible assets are
It is unclear what the word "consists" refers to

2024-02-28 11:51 UTC, MartinSchmidt commented on README.md
> +The GCs are issued by an issuing body and are stored in a registry. And an owner keeps track of their ownership of GC slices in a wallet. The process of issuing a GC is a complex process that involve
All the public data, as in, the transactions are stored and available on the registries.

The wallet stores the ownes private data regarding their GCs.

2024-02-28 11:52 UTC, MartinSchmidt commented on doc/example-api.md
> +## Create a recipient
Sure, will probably come, this was more to show a list of example APIs to begin highlighting what could be possible, not a complete list.

2024-02-28 11:52 UTC, MartinSchmidt commented on README.md
> +In the Project-Origin Electricity implementation, consists of a fungible and non-fungible digital assets, where the non-fungible assets are called Guarantees of Origin (GCs). The fungible assets are
rewrote it

2024-02-28 11:54 UTC, MartinSchmidt commented on README.md
> +The GCs are issued by an issuing body and are stored in a registry. And an owner keeps track of their ownership of GC slices in a wallet. The process of issuing a GC is a complex process that involve
The stamp service should be thought of as a service an TSO or other issuing body can self-host and use. 
It won't enable others to issue certificates, unless that is accepted within the given network (Energy Track and Trace).

So think of it as a tool to make the process easier for a Issuing body, not something other people would be able to use.

2024-02-28 18:56 UTC, sahma19 approved these changes

2024-03-01 12:57 UTC, merged